In [1]:
import pandas as pd
import plotly.express as px

from dash import html
from dash import dcc
import dash
from dash.dependencies import Input, Output, State

In [2]:
data=pd.read_csv("dataforscatter.csv")
data.head()

,Unnamed: 0,dbn,school_name,borough,location,trees,crashes,pc,shootings,arrests,programs,bins,demographic_category,cohort_year,total_grads_of_cohort
0,0,01M292,Henry Street School for International Studies,Manhattan,"(40.713684, -73.986336)",3.0,21.0,5.0,14.0,73.0,17.0,1.0,All Students,2013.0,69.4
1,1,01M292,Henry Street School for International Studies,Manhattan,"(40.713684, -73.986336)",3.0,21.0,5.0,14.0,73.0,17.0,1.0,All Students,2012.0,54.5
2,2,01M292,Henry Street School for International Studies,Manhattan,"(40.713684, -73.986336)",3.0,21.0,5.0,14.0,73.0,17.0,1.0,All Students,2011.0,63.0
3,3,01M292,Henry Street School for International Studies,Manhattan,"(40.713684, -73.986336)",3.0,21.0,5.0,14.0,73.0,17.0,1.0,All Students,2010.0,42.6
4,4,01M292,Henry Street School for International Studies,Manhattan,"(40.713684, -73.986336)",3.0,21.0,5.0,14.0,73.0,17.0,1.0,All Students,2009.0,57.6

In [3]:
list_loc = data["location"].to_list()
list_loc = [x.split(",") for x in list_loc]
list_lat=[x[0] for x in list_loc]
list_lat=[x.split("(") for x in list_lat]
list_lat=[float(x[1]) for x in list_lat]
data["latitude"]=list_lat

In [4]:
list_long=[x[1] for x in list_loc]
list_long=[x.split(")") for x in list_long]
list_long=[float(x[0]) for x in list_long]
data["longitude"]=list_long

In [ ]:
app = dash.Dash(__name__)


app.layout = html.Div([
        html.Div([html.Span("Map of New York City & the schools"),
            dcc.Graph(id="map", figure={}),     #id to manipulate the graph later
            dcc.Dropdown(
            id="Borough",
            options=[    
                {"label": "Bronx", "value": "Bronx"},
                {"label": "Brooklyn", "value": "Brooklyn"},
                {"label": "Manhattan", "value": "Manhattan"},
                {"label": "Queens", "value": "Queens"},
                {"label": "Staten Island", "value": "Staten Island"},
                {"label": "All", "value":"all"}
            ],
            value="all",
            searchable=False,
            style={'width': '40%', 'height': '35px'},
            placeholder="Please select area"          
                        )])
])
@app.callback(
    Output(component_id="map", component_property="figure"),
    Input(component_id="Borough", component_property="value"))
    
def update_map(borough_chosen):  #input #starts statement
    if borough_chosen=="all":
        df=data
        zoom=9.5
    else:
        df=data[(data["borough"]==borough_chosen)]
        zoom=10
    
    fig=px.scatter_mapbox(df, lat="latitude", lon="longitude", 
                    hover_name="school_name", hover_data=["cohort_year", "total_grads_of_cohort"],
                    color_discrete_sequence=["fuchsia"], zoom=zoom, height=600, width=800)
    fig.update_layout(mapbox_style="open-street-map")
    fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
    return fig  #component_property of output


if __name__ == '__main__':
    app.run_server(debug=False)

Dash is running on http://127.0.0.1:8050/

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off

 * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
127.0.0.1 - - [27/Jan/2022 10:41:37] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [27/Jan/2022 10:41:37] "GET /_dash-component-suites/dash/deps/polyfill@7.v2_0_0m1642785127.12.1.min.js HTTP/1.1" 200 -
127.0.0.1 - - [27/Jan/2022 10:41:37] "GET /_dash-component-suites/dash/deps/react@16.v2_0_0m1642785127.14.0.min.js HTTP/1.1" 200 -
127.0.0.1 - - [27/Jan/2022 10:41:37] "GET /_dash-component-suites/dash/deps/react-dom@16.v2_0_0m1642785127.14.0.min.js HTTP/1.1" 200 -
127.0.0.1 - - [27/Jan/2022 10:41:37] "GET /_dash-component-suites/dash/deps/prop-types@15.v2_0_0m1642785127.7.2.min.js HTTP/1.1" 200 -
127.0.0.1 - - [27/Jan/2022 10:41:37] "GET /_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_0_0m1642785125.min.js HTTP/1.1" 200 -
127.0.0.1 - - [27/Jan/2022 10:41:37] "GET /_dash-component-suites/dash/dcc/dash_core_components.v2_0_0m1642785127.js HTTP/1.1" 200 -
127.0.0.1 - - [27/Jan/2022 10:41:37] "GET /_dash-component-suites/dash/dcc/dash_core_components-shared.v2_0_0m1642785127.js HTTP/1.1" 200 -
127.0.0.1 - - [27/Jan/2022 10:41:37] "GET /_dash-component-suites/dash/html/dash_html_components.v2_0_0m1642785127.min.js HTTP/1.1" 200 -
127.0.0.1 - - [27/Jan/2022 10:41:37] "GET /_dash-component-suites/dash/dash_table/bundle.v5_0_0m1642785126.js HTTP/1.1" 200 -
127.0.0.1 - - [27/Jan/2022 10:41:38] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [27/Jan/2022 10:41:38] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [27/Jan/2022 10:41:38] "GET /_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1" 304 -
127.0.0.1 - - [27/Jan/2022 10:41:38] "GET /_dash-component-suites/dash/dcc/async-dropdown.js HTTP/1.1" 304 -
127.0.0.1 - - [27/Jan/2022 10:41:38] "GET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1" 304 -
127.0.0.1 - - [27/Jan/2022 10:41:38] "GET /_favicon.ico?v=2.0.0 HTTP/1.1" 200 -
127.0.0.1 - - [27/Jan/2022 10:41:40] "POST /_dash-update-component HTTP/1.1" 200 -